version: "3"
name: litefs-benchmark
services:
  nginx:
    build:
      context: ./docker-config/nginx
      dockerfile: Dockerfile.litefs
    ports:
      - "8080:80"
  primary:
    build:
      context: .
      dockerfile: Dockerfile.litefs
      args:
        - "LITEFS_CONFIG=litefs.static-lease.yml"
    ports:
      - "8081:8081"
    privileged: true
    environment:
      FLY_REGION: primary
      IS_PRIMARY: "true"
  replica1:
    build:
      context: .
      dockerfile: Dockerfile.litefs
      args:
        - "LITEFS_CONFIG=litefs.static-lease.yml"
    ports:
      - "8082:8081"
    privileged: true
    environment:
      FLY_REGION: replica1
      IS_PRIMARY: "false"
