version: "3"
name: postgres-benchmark
services:
  nginx:
    build:
      context: ./docker-config/nginx
      dockerfile: Dockerfile.postgres
    ports:
      - "8080:80"
    depends_on:
      - app-primary
      - app-replica
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    command: >
      postgres -c wal_level=replica -c max_wal_senders=10 -c hot_standby=on
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
  postgres-replica:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    command: >
      postgres -c hot_standby=on -c primary_conninfo='host=postgres-primary port=5432 user=appuser password=secret'
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
  app-primary:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      FLY_REGION: primary
      IS_PRIMARY: "true"
    ports:
      - "8081:8081"
    depends_on:
      - postgres-primary

  app-replica:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      FLY_REGION: replica1
      IS_PRIMARY: "false"
    ports:
      - "8082:8081"
    depends_on:
      - postgres-replica
